title: Does poly coated urea fertilizer application reduce nitrate loss from tile drainage?
description: ABE 516x Final Project by Eric Henning
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
