title: Does poly coated urea fertilizer reduce flow-weighted nitrate concentration in tile drainage?
description: ABE 516x Final Project by Eric Henning
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
